name: Deploy and Remove Serverless App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'handler.py'
      - 'serverless.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Serverless deploy
        run: npx serverless deploy --stage $ENVIRONMENT --region $AWS_DEFAULT_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # remove:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - name: Remove Serverless deployment
  #       run: npx serverless remove --stage $ENVIRONMENT --region $AWS_DEFAULT_REGION
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
